version: '3.8'

volumes:
  mysql_data:

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: UNICAMP2022
      MYSQL_DATABASE: INF335
      MYSQL_USER: nicole
      MYSQL_PASSWORD: UNICAMP2022
      MYSQL_TCP_PORT: 3306
    ports:
      - 3306:3306
    expose:
      - 3306
  mongo:
    image: mongo
    restart: always
    volumes:
      - mysql_data:/var/lib/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: UNICAMP2022
    ports:
      - 27017:27017
    expose:
      - 27017